### ISSUE TITLE
White Shirt Wont Change/Still No Peds

### ISSUE THREAD

**Issue by ch0sguy** [Enzo-DC/qb-clothes#4]
Peds are not spawning at any of the coordinates listed in the config, tried to import one directly using qb-target using a different model and it worked fine, so its not an issue with my qb-target; this isnt too much of an issue, as I can just replace all peds if need be, its just tedious

The primary issue im having is with the clothing variant, no matter what field I modify, whether it be shirt or jacket, my playermodel still has this solid white shirt on? I can't seem to remove it in any of the settings.
![whiteshirt](https://user-images.githubusercontent.com/62267705/152677277-161d4fe6-0e7e-459d-9cf0-0d5ed929e067.PNG)

**Comment by Enzo-DC** [comment]
the ped model is for a 2189 gamebuild. now i update the readme so you know.

for the white shirt? you are the first and perhaps the only one to have this problem. do you have addon clothes? have you tried to set tshirt 15 or jacket 15?

**Comment by ch0sguy** [comment]
I see the issue now, its the whole GTA V undershirt and overshirt options, I just had to set them to the correct values to make that default shirt disappear; is there a way to set a black list for certain clothing items or categories, such as only allowing players to select from 5 shirt options and 4 pant options, but no scarfs or necklaces (I haven't really gone through the code entirely yet, I just figured I'd ask to save some time)?
